name: run-postman

on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:

jobs:
  run-postman:
    name: Run Postman
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
      - uses: actions/checkout@main
      - name: Run postman collection
      - uses: matt-ball/newman-action@master
        with:
          collection: postman_collection.json